package capital.dashboard

data class Scenario(
    val id: String,
    val title: String,
    val category: String,
    val description: String,
    val steps: List<String>,
)

private fun scenario(
    id: String,
    title: String,
    category: String,
    description: String,
    vararg steps: String,
) = Scenario(id, title, category, description, steps.toList())

val scenarios =
    listOf(
        scenario(
            "happy",
            "A normal advance",
            "Money movement",
            "Reserve capacity, fund once, and match the bank debit to the ledger.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Dispatch to the bank",
            "Reconcile payment",
        ),
        scenario(
            "lost-held",
            "Paid, but the response vanished",
            "Recovery",
            "The bank paid. A new hold allows queries, but no resubmission.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Lose response after bank payment",
            "Apply a new risk hold",
            "Recover by query",
            "Replay and reconcile",
        ),
        scenario(
            "not-found-held",
            "Unknown outcome + hold",
            "Recovery",
            "No bank record is found. Reservations remain until the hold clears and recovery can proceed.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Lose response before execution",
            "Apply a new risk hold",
            "Query only; keep reservation",
            "Clear hold and recover same key",
            "Reconcile payment",
        ),
        scenario(
            "retry",
            "Retry with the same identity",
            "Recovery",
            "An unknown operation is absent at the bank; an eligible recovery retries its frozen key.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Lose response before execution",
            "Recover with same bank key",
            "Reconcile payment",
        ),
        scenario(
            "crash",
            "Worker stops after bank payment",
            "Recovery",
            "Simulate interruption after the HTTP call, before the local posting. The integration suite also tests an actual JVM halt.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Interrupt after bank execution",
            "Expire lease and recover",
            "Reconcile payment",
        ),
        scenario(
            "rejected",
            "Bank rejects the payment",
            "Bank integration",
            "A definite rejection releases the reservation and creates no funding journal.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Receive bank rejection",
            "Reconcile payment",
        ),
        scenario(
            "hold-before",
            "Hold before dispatch",
            "Risk monitoring",
            "A provably undispatched payment is canceled and its reservation released.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Apply hold before dispatch",
            "Dispatch recheck",
            "Reconcile payment",
        ),
        scenario(
            "destination",
            "Destination changes",
            "Bank integration",
            "The frozen destination cannot be silently replaced.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Change verified destination",
            "Dispatch recheck",
            "Reconcile payment",
        ),
        scenario(
            "stale",
            "Fresh download, old coverage",
            "Underwriting",
            "The report download is current, but its reporting period is behind.",
            "Assess stale report",
            "Attempt reservation",
            "Inspect unchanged balances",
        ),
        scenario(
            "refund",
            "Refunds erase capacity",
            "Underwriting",
            "Net proceeds fall to $700 with $600 outstanding: $40 exposure exceeds the new limit.",
            "Assess revised proceeds",
            "Attempt reservation",
            "Inspect unchanged balances",
        ),
        scenario(
            "fraud",
            "Revenue spike → review",
            "Fraud review",
            "An illustrative 3× velocity rule creates a hold. A revenue spike is not proof of fraud.",
            "Evaluate velocity signal",
            "Attempt reservation",
            "Inspect unchanged balances",
        ),
        scenario(
            "cancellations",
            "Cancellations increase",
            "Risk monitoring",
            "Cancellations above the illustrative 10% threshold pause advances for review.",
            "Evaluate cancellation signal",
            "Attempt reservation",
            "Inspect unchanged balances",
        ),
        scenario(
            "liquidity",
            "Credit available, cash unavailable",
            "Money movement",
            "Eligible credit does not imply sufficient funding-account cash.",
            "Assess eligibility",
            "Attempt reservation",
            "Inspect unchanged balances",
        ),
        scenario(
            "race",
            "Eight requests, one capacity pool",
            "Concurrency",
            "Eight concurrent database clients compete for the last $200 of principal capacity.",
            "Assess eligibility",
            "Race eight distinct requests",
            "Dispatch the winning reservation",
            "Reconcile payment",
        ),
        scenario(
            "duplicate",
            "Eight copies of one request",
            "Concurrency",
            "Concurrent duplicate keys return one durable operation. A changed amount conflicts.",
            "Assess eligibility",
            "Race eight identical requests",
            "Try a conflicting payload",
            "Dispatch once",
            "Replay and reconcile",
        ),
        scenario(
            "mismatch",
            "Bank statement discrepancy",
            "Reconciliation",
            "A deliberately altered statement copy differs by $1. The exception stays open; no journal is rewritten.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Dispatch to the bank",
            "Import a mismatching statement",
        ),
        scenario(
            "collection",
            "Store collection and repayment",
            "Reconciliation",
            "Match a final $1,000 receipt, repay $800 principal, and leave $200 payable to the developer.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Dispatch to the bank",
            "Match final store collection",
            "Replay collection; no second repayment",
        ),
        scenario(
            "shortfall",
            "Final collection is short",
            "Reconciliation",
            "A final $700 report and receipt repay $700 of $800 outstanding. Keep the $100 shortfall and close the pool.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Dispatch to the bank",
            "Allocate the final $700 receipt",
            "Replay collection; retain shortfall",
        ),
        scenario(
            "collection-mismatch",
            "Store report ≠ bank receipt",
            "Reconciliation",
            "A $1,000 report and $995 credit remain unapplied. Never invent a $5 fee to force a match.",
            "Assess eligibility",
            "Reserve $200 principal",
            "Dispatch to the bank",
            "Compare report and collection",
            "Keep exception open",
        ),
        scenario(
            "public-data",
            "Replay a real retail day",
            "Public dataset",
            "Replay UCI sales/cancellations through illustrative rules, then simulated USD payments. No app-store or fraud labels.",
            "Normalize and assess selected day",
            "Attempt advance reservation",
            "Dispatch if eligible",
            "Reconcile payment",
        ),
    )
